- easylinks/src/main/java/com/google/step/servlets/ServletHelper.java
We could add some helper method or variables that will be used in multiple  servlets to this helper class.
Now, I'm only thinking the Datastore and Gson will be used a lot in multiple servlets, we could add more later on.
> Add a helper class that could contains the commonly used helper method.

- easylinks/src/main/java/com/google/step/servlets/LoginServlet.java
- easylinks/src/main/java/com/google/step/servlets/placeholder.txt
- easylinks/src/main/webapp/script.js
Login Servlet returns
- link to the login page if not logged in
- "okay-columbia" if user is logged in with a columbia school email, since we need our user to be a verified columbia student in order to use some services
- "okay" if user is logged in with some other email
> Add Login Servlet to check user authentication and corresponding js function

- easylinks/src/main/java/com/google/step/servlets/DeleteLinkServlet.java
- easylinks/src/main/webapp/script.js
The parameter of the JavaScript function may change depending on how the links are displayed.
> Add Delete functionality.

- easylinks/src/main/java/com/google/step/servlets/EasyLinkServlet.java
- easylinks/src/main/webapp/index.html
I add some feature and codes so that we could test our code and the datastore. 
We could change or delete those later.
> Add some basic design to the web and a redirect servlet.

- easylinks/src/main/webapp/manage.html
- easylinks/src/main/webapp/script.js
- easylinks/src/main/webapp/style.css
Haven't implemented the Servlet side of the Edit feature. May wait till the Add feature gets implemented to see how links are stored in the DataStore.
> Add a form to record edited links.

- easylinks/src/main/java/com/google/step/servlets/ManageServlet.java
- easylinks/src/main/webapp/manage.html
- easylinks/src/main/webapp/script.js
- Add FetchOption argument to asList()
- Modify manage.html and script.js so that the headers of the link table are not removed
> Fix two bugs for the display functionality

- easylinks/src/main/java/com/google/step/servlets/ManageServlet.java
- easylinks/src/main/webapp/manage.html
- easylinks/src/main/webapp/script.js
- easylinks/src/main/webapp/style.css
These functions should now work properly.
> Fix bugs in Delete and Edit.

- easylinks/src/main/webapp/index.html
- easylinks/src/main/webapp/script.js
- easylinks/src/main/webapp/style.css
UI looks like:
Feel free to make it prettier:))
I also added userAuth() when redirecting to the manage page
> Finish frontend design for home page

- easylinks/src/main/java/com/google/step/servlets/EasyLinkServlet.java
- easylinks/src/main/java/com/google/step/servlets/ManageServlet.java
- easylinks/src/main/java/com/google/step/servlets/ServletHelper.java
Also, add some code to make sure no repeating shortcut will be added to the datastore.
> Add code to process the private link and redirect to that url.

- easylinks/src/main/webapp/index.html
- easylinks/src/main/webapp/manage.html
- easylinks/src/main/webapp/script.js
- easylinks/src/main/webapp/style.css
> Finish Frontend Design for management page

- easylinks/src/main/webapp/index.html
- easylinks/src/main/webapp/manage.html
- easylinks/src/main/webapp/script.js
- easylinks/src/main/webapp/style.css
- Added a button on the Management Page to redirect back to homepage.
- Reformatted Edit form to align with Add form.
- Fixed possible conflict between Add and Edit forms.
> Add changes to frontend design.

- easylinks/src/main/webapp/WEB-INF/index.yaml
Create a index.yaml file so that the we can display the existing links properly.
> Fix the bug when deploy the project.

- easylinks/src/main/java/com/google/step/servlets/LoginServlet.java
- easylinks/src/main/java/com/google/step/servlets/ManageServlet.java
- easylinks/src/main/java/com/google/step/servlets/RedirectionServlet.java
- easylinks/src/main/webapp/manage.html
- easylinks/src/main/webapp/script.js
- We use /login as mapping for loginServlet, this could result in a conflict as our user may also use login as a customized shortcut, the same for the manageServlet. Appending a "~" before the mapping for internal servlets can resolve this issue.
- I also change a few namings so that they can better reflect the functionality.
> Resolve a potential conflict between user input shortcut and internal servlets

- easylinks/src/main/java/com/google/step/servlets/NavigateServlet.java
- easylinks/src/main/webapp/WEB-INF/columbiaU_buildings.csv
doGet() doesn't do anything for now, it's here just for testing.
> Upload the building code file. And test the file is uploaded correctly.

- easylinks/src/main/webapp/calendar.html
- easylinks/src/main/webapp/calendar_script.js
- easylinks/src/main/webapp/style.css
Note that the origin should be user's current location, but for ease of testing and better visualization, I currently fix it to somewhere on the Columbia campus.
demo:
> Add Navigation functionality to the event page

- easylinks/src/main/java/com/google/step/servlets/PeopleSearchServlet.java
- easylinks/src/main/webapp/people.html
- easylinks/src/main/webapp/people_script.js
The webpage should display all qualified email addresses when ~who/* is entered. Since I still cannot see the correct redirection, I could not check whether this functions as expected. I'll try to solve that problem later.
> Add People Search feature.

- easylinks/src/main/java/com/google/step/servlets/NavigateServlet.java
- easylinks/src/main/webapp/navigation.html
- easylinks/src/main/webapp/navigation_script.js
- easylinks/src/main/webapp/style.css
The current UI is https://screenshot.googleplex.com/Qpzze9AFYnB.png
Navigation will be implemented later, for now it will show the location on the google map with a button for the navigation.
> Finish the basic navigation function.

- easylinks/src/main/java/com/google/step/servlets/CalendarServlet.java
- easylinks/src/main/webapp/calendar.html
- easylinks/src/main/webapp/calendar_script.js
- easylinks/src/main/webapp/style.css
> Add the "Calculate set off time" feature

- easylinks/src/main/webapp/WEB-INF/columbiaU_buildings.csv
- easylinks/src/main/webapp/navigation_script.js
Now by clicking the direction icon, the route to that building will be shown.
For now, I'm only using the test location, not the current location.
The screen shot is https://screenshot.googleplex.com/6d8ANw6izyo.png
> Finish the navigation feature.

- easylinks/src/main/java/com/google/step/servlets/PeopleSearchServlet.java
The UI for when no results are found:
> Deal with no-result situation

- easylinks/src/main/webapp/navigation.html
- easylinks/src/main/webapp/navigation_script.js
- easylinks/src/main/webapp/style.css
The current UI is https://screenshot.googleplex.com/FXiQEgtJyep.png
> Add the error message when the directions not found.

- easylinks/src/main/webapp/calendar.html
- easylinks/src/main/webapp/calendar_script.js
- easylinks/src/main/webapp/index.html
- easylinks/src/main/webapp/style.css
- Add button on event page to redirect back to the home page
- Add navigation and set off time calculation from the user's current location
- Deal with error cases on navigation and set off time calculation
> Enhance the calendar feature

- easylinks/src/main/java/com/google/step/servlets/PeopleSearchServlet.java
- easylinks/src/main/webapp/style.css
UI for no-matching-result:
UI for several-matching-results:
> Add style to the People Search pages.

- easylinks/src/main/java/com/google/step/servlets/NavigateServlet.java
- easylinks/src/main/webapp/navigation.html
- easylinks/src/main/webapp/navigation_script.js
- easylinks/src/main/webapp/style.css
Add the error check if user doesn't type in the building abbreviation. If so, the map will search the building name the user type in.
> Add the back button and the error check for the navigation function.

- easylinks/src/main/java/com/google/step/servlets/PeopleSearchServlet.java
The UI currently looks like this:
> Gives information on setting up the default email client.

- easylinks/src/main/webapp/calendar.html
- easylinks/src/main/webapp/calendar_script.js
- fix the handleClientOnload() not defined error
- clear all page content after the user signs out
> Fix two issues with the Calendar feature

- easylinks/src/main/webapp/script.js
Home page can either be xxx.com/index.html or simply xxx.com
Fix the code to include the xxx.com case
> Fix the sign in button not shown issue

- easylinks/src/main/webapp/manage.html
- easylinks/src/main/webapp/script.js
- easylinks/src/main/webapp/style.css
Set default display links to 20 and allow users to navigate between pages using prev and next buttons
UI looks like: https://screenshot.googleplex.com/gV4ZzMS9oBN
> Allow page navigation on manage.html

- easylinks/src/main/webapp/script.js
> Hide link id

- easylinks/src/main/java/com/google/step/servlets/ManageServlet.java
- easylinks/src/main/java/com/google/step/servlets/PublicLinkServlet.java
- easylinks/src/main/java/com/google/step/servlets/ServletHelper.java
- easylinks/src/main/webapp/display.html
- easylinks/src/main/webapp/display_script.js
- easylinks/src/main/webapp/manage.html
- easylinks/src/main/webapp/style.css
Current UI of display https://screenshot.googleplex.com/Ucm2BJOcgVn.png
Current UI of manage https://screenshot.googleplex.com/y29Q54JdeOw.png
> Finish displaying the already created public links.

- easylinks/src/main/webapp/script.js
> Fix the bug that only the first id gets hidden

- easylinks/src/main/webapp/display.html
- easylinks/src/main/webapp/display_script.js
> Chnage the place for displaying public link.

- easylinks/src/main/java/com/google/step/servlets/ManageServlet.java
- easylinks/src/main/java/com/google/step/servlets/PublicLinkServlet.java
- easylinks/src/main/webapp/display.html
- easylinks/src/main/webapp/display_script.js
- easylinks/src/main/webapp/script.js
> Add go-private feature.

- easylinks/src/main/webapp/display_script.js
Please let me know if anything wrong comes up again. Really unsure how it works.
> Fix unhidden id.

- easylinks/src/main/webapp/display_script.js
- easylinks/src/main/webapp/manage.html
- easylinks/src/main/webapp/navigation_script.js
- easylinks/src/main/webapp/script.js
- easylinks/src/main/webapp/style.css
The current UI of displaying public links https://screenshot.googleplex.com/aa94325b-9032-4aa8-a2e7-78edd71c1dcc.png
> Add word-break to the display links, remove unneeded code.

- easylinks/src/main/java/com/google/step/servlets/RedirectionServlet.java
- easylinks/src/main/webapp/manage.html
- easylinks/src/main/webapp/style.css
Current UI: https://screenshot.googleplex.com/bda64dd0-0d51-4f60-aca7-c71054bf280e
> Improve styling for add and edit form AND add alert message when no url is found

- easylinks/src/main/webapp/manage.html
- easylinks/src/main/webapp/script.js
In case there are so many links, we allow the user to search for links by shortcut.
UI looks like: https://screenshot.googleplex.com/b02b83d2-4896-44ba-a2d0-1e4de026356c
> Add search by shortcut functionality on management page

- easylinks/src/main/webapp/display_script.js
- easylinks/src/main/webapp/index.html
> Allow viewing public links through the main page.

- easylinks/src/main/java/com/google/step/servlets/ManageServlet.java
- easylinks/src/main/webapp/display.html
- easylinks/src/main/webapp/display_script.js
- easylinks/src/main/webapp/index.html
- easylinks/src/main/webapp/manage.html
- easylinks/src/main/webapp/script.js
> Manage private and public links on the same page.

- easylinks/src/main/java/com/google/step/servlets/PeopleSearchServlet.java
- easylinks/src/main/webapp/WEB-INF/index.yaml
- easylinks/src/main/webapp/style.css
The live server should be working now.
> Updating index.yaml
